# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypto Lemon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto Lemon

	pod 'Alamofire'
	pod 'SDWebImage'
	pod 'SwiftKeychainWrapper', '~> 3.0'
	pod 'Charts'
	pod 'RLBAlertsPickers', '~> 1.1.1'
	pod 'RealmSwift', '~> 3.18.0'	


  target 'Crypto LemonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crypto LemonUITests' do
    # Pods for testing
  end

end
